export const rain = document.getElementById('cardRain')
export const forest = document.getElementById('cardForest')
export const marketplace = document.getElementById('cardMarketplace')
export const campfire = document.getElementById('cardCampfire')
export const buttons = document.getElementById('buttons')
export const minutes = document.getElementById('minutes')
export const seconds = document.getElementById('seconds')
export const cards = document.getElementById('card')
